CREATE TABLE PRODUCTO(
    ID_PRODUCTO NUMBER,
    NOMBRE NVARCHAR2(100),
    CATEGORIA_ID NUMBER,--1. TECNLOGIA, 2. HOGAR, 3. ROPA, 4. JUGUETERIA, 5. FARMACIA
    PRECIO NUMBER,
    STOCK NUMBER,
    MARCA NVARCHAR2(100),
    CONSTRAINT PRODUCTO_PK PRIMARY KEY (ID_PRODUCTO)
);

SELECT * FROM PRODUCTO;
DELETE PRODUCTO;

INSERT INTO PRODUCTO VALUES(1, 'LAPTOP LENOVO',1,18500,10,'LENOVO');
INSERT INTO PRODUCTO VALUES(2, NULL,NULL,NULL,NULL,NULL);
INSERT INTO PRODUCTO VALUES(3, 'PLAYERA NIKE',3,950,25,'NIKE');
INSERT INTO PRODUCTO VALUES(4, 'PANTALON',3,400,50,'LEVIS');
INSERT INTO PRODUCTO VALUES(5, 'AUDIFONO',1,800,100,'BEATS SOUND');
INSERT INTO PRODUCTO VALUES(6, 'TENIS ADIDAD',3,900,50,'ADIDAS');
INSERT INTO PRODUCTO VALUES(7, 'SUDADERA PUMA',3,600,100,'PUMA');
INSERT INTO PRODUCTO VALUES(8, 'JUEGO DE MESA',4,1200,20,'FOTORAMA');
INSERT INTO PRODUCTO VALUES(9, 'XBOX',1,6000,50,'MICROSOFT');
COMMIT;

//ACTIVIDADES

//1. MOSTRAR NOMBRE DE LA CATEGORIA USANDO CASE
SELECT ID_PRODUCTO, NOMBRE,(
    CASE CATEGORIA_ID
    WHEN 1 THEN 'TECNOLOGIA'
    WHEN 2 THEN 'HOGAR'
    WHEN 3 THEN 'ROPA'
    WHEN 4 THEN 'JUGETERIA'
    WHEN 5 THEN 'FARMACIA'    
    ELSE 'CATEGORIA NO DEFINIDA'
    END
)AS CATEGORIA, PRECIO,STOCK,MARCA FROM PRODUCTO;


//2. CLASIFICAR PRODUCTOS SEGUN SU PRECIO (CARO MEDIO ECONOMICO)
SELECT ID_PRODUCTO, NOMBRE,CATEGORIA_ID,PRECIO,(
    CASE
    WHEN PRECIO > 10000 THEN 'CARO' 
    WHEN PRECIO <= 9999 AND PRECIO >1000 THEN 'MEDIO'
    WHEN PRECIO <= 1000 THEN 'BARATO' 
    ELSE 'PRECIO NO DEFINIDO'
    END
)AS PRECIO_TEXTO, STOCK, MARCA FROM PRODUCTO;

//3. CLASIFICAR PRODUCTOS POR DIPONIBILIDAD DE STOCK(AGOTADO, BAJO STCOK, STOCK INSUFICIENTE)
SELECT ID_PRODUCTO, NOMBRE,CATEGORIA_ID,PRECIO,STOCK,(
    CASE
    WHEN STOCK = 0 THEN 'AGOTADO' 
    WHEN STOCK <= 50 THEN 'BAJO STOCK'
    WHEN STOCK > 50 THEN 'STOCK SUFICIENTE' 
    ELSE 'STOCK NO DEFINIDO'
    END
)AS STOCK_TEXTO, MARCA FROM PRODUCTO;

//4. MENSAJE COMPUESTO USANDO CASE Y CONCATENACION (PARA STOCK)
SELECT ID_PRODUCTO, NOMBRE,CATEGORIA_ID,PRECIO,(
    CASE
    WHEN STOCK = 0 THEN 'EL PRODUCTO ESTA AGOTADO: ' || STOCK || ' DISPONIBLES'
    WHEN STOCK <= 50 THEN 'EL PRODUCTO ESTA BAJO STOCK: ' || STOCK || ' DISPONIBLES'
    WHEN STOCK > 50 THEN 'HAY PRODUCTOS SUFICIENTES: ' || STOCK || ' DISPONIBLES'
    ELSE 'STOCK NO DEFINIDO'
    END
)AS STOCK_TEXTO, MARCA FROM PRODUCTO;

//5. USAR CASE PARA CLASIFICAR POR PRECIO Y POR STOCK SI ES COSTOSO Y SI ESTA DISPONIBLE
SELECT ID_PRODUCTO, NOMBRE,CATEGORIA_ID,PRECIO,STOCK,(
    CASE
    WHEN PRECIO > 10000 THEN 'CARO ' 
    WHEN PRECIO <= 9999 AND PRECIO >1000 THEN 'MEDIO '
    WHEN PRECIO <= 1000 THEN 'BARATO ' 
    ELSE 'PRECIO NO DEFINIDO - '
    END
) ||(
    CASE
        WHEN STOCK = 0 THEN 'AGOTADO'
        WHEN STOCK <= 20 THEN 'BAJO STOCK'
        WHEN STOCK > 50 THEN 'PRODUCTOS SUFICIENTES'
        ELSE 'STOCK NO DEFINIDO'
    END
)AS CLASIFICACION_STOCK_PRECIO, MARCA FROM PRODUCTO ORDER BY PRECIO;
