--EJERCICIO DE PRACTICA USANDO CASE Y JOINS

--TABLA PADRE
CREATE TABLE TALLER(
    ID_TALLER NUMBER,
    TITULO NVARCHAR2(100),
    NIVEL NUMBER, --1. BASICO, 2. INTEMRMEDIO, 3.AVANZACO
    DURACION_HR NUMBER,
    INSTRUCTOR NUMBER, --1.ALMA, 2. CEICILIA, 3. BRUNO, 4. DAVID, 5. ESTELA, 6. FERNANDO
    CONSTRAINT TALLER_PK PRIMARY KEY (ID_TALLER)
);

//TABLA HIJO
CREATE TABLE PARTICIPANTE(
    ID_PARTICIPANTE NUMBER,
    NOMBRE NVARCHAR2(100),
    APELLIDO NVARCHAR2(100),
    EDAD NUMBER,
    OCUPACION NUMBER,--1. ESTUDIANTE, 2. DOCENTE, 3. EMPRENDEDOR, 4. PROFESIONAL INDEPENDIENTE, 5. EMPLEADO
    TALLER_ID NUMBER,
    CONSTRAINT PARTICIPANTE_PK PRIMARY KEY (ID_PARTICIPANTE),
    CONSTRAINT TALLER_FK FOREIGN KEY (TALLER_ID) REFERENCES TALLER(ID_TALLER)
);

INSERT INTO TALLER VALUES(1,'TALLER DE ORATORIA',2,10,1);
INSERT INTO TALLER VALUES(2,'INTRODUCCION A PYTHON',0,20,0);
INSERT INTO TALLER VALUES(3,'TALLER DE PINTURA',2,15,3);
INSERT INTO TALLER VALUES(4,'TALLER DE BAILE',3,40,5);
INSERT INTO TALLER VALUES(5,'TALLER DE MATERIALES', 3, 40, 5);
INSERT INTO TALLER VALUES(6,'TALLER DE COCINA', 1, 25, 3);
INSERT INTO TALLER VALUES(7,'TALLER DE PROGRAMACIÓN', 3, 20, 2);
INSERT INTO TALLER VALUES(8,'TALLER DE PRIMEROS AUXILIOS', 3, 15, 3);
COMMIT;

INSERT INTO PARTICIPANTE VALUES(1,'LUISA', 'CARRILLO',24,2,1);
INSERT INTO PARTICIPANTE VALUES(2,'OMAR',NULL,32,0,NULL);
INSERT INTO PARTICIPANTE VALUES(3,'DIANA', 'VAZQUEZ',21,1,7);
INSERT INTO PARTICIPANTE VALUES(4,'VIVIAN', 'CARMONA',26,5,2);
INSERT INTO PARTICIPANTE VALUES(5,'ARTURO', 'SANCHEZ', 29,4,4);
INSERT INTO PARTICIPANTE VALUES(6,'FERNANDO', 'ROSAS', 31,5,7);
INSERT INTO PARTICIPANTE VALUES(7,'ANA', 'RODRÍGUEZ', 22, 3, 3);
INSERT INTO PARTICIPANTE VALUES(8,'JORGE', 'SALGADO', 28, 4, 5);
COMMIT;

SELECT * FROM PARTICIPANTE;
SELECT * FROM TALLER ORDER BY duracion_hr;


//ACTIVIDADES
//1. MOSTRAR LOS REGISTROS DE LOS PARTICIPANTES JUNTO AL  NOMBRE DEL TALLER USANDO CASE PARA MOSTRAR EL NOMBRE DEL INSTRUCTOR Y LA OCUPACION
SELECT ID_PARTICIPANTE,NOMBRE,APELLIDO,EDAD,OCUPACION,(
CASE OCUPACION
    WHEN 1 THEN 'ESTUDIANTE'
    WHEN 2 THEN 'DOCENTE'
    WHEN 3 THEN 'EMPRENDEDOR'
    WHEN 4 THEN 'PROFESIONAL INDEPENDIENTE'
    WHEN 5 THEN 'EMPLEADO'
    ELSE 'OCUPACION NO REGISTRADA'
    END
)AS OCUPACION_NOM, TALLER_ID,(
CASE TALLER_ID
    WHEN 1 THEN 'ALMA'
    WHEN 2 THEN 'CECILIA'
    WHEN 3 THEN 'BRUNO'
    WHEN 4 THEN 'DAVID'
    WHEN 5 THEN 'ESTELA'
    WHEN 6 THEN 'FERNANDO'
    ELSE 'INSTRUCTOR NO REGISTRADO'
    END
)AS NOM_INSTRUCTOR FROM PARTICIPANTE;

//2. CONTAR CUANTOS PARTICIPANTES HAY POR TALLER
SELECT TALLER_ID, COUNT (ID_PARTICIPANTE) AS PARTICIPANTES_POR_TALLER FROM PARTICIPANTE WHERE TALLER_ID IS NOT NULL GROUP BY TALLER_ID;

//3. MOSTRAR LOS TALLERES CON MAYOR DURACION Y CONCATENAR LA PALABRA "HORAS" AL FINAL
SELECT ID_TALLER, TITULO, NIVEL, (DURACION_HR || ' HORAS') AS DURACION, INSTRUCTOR FROM TALLER WHERE DURACION_HR > 20;

//4. MOSTRAR EL NOMBRE DEL INSTRUCTOR QUE IMPARTE MAS TALLERES
SELECT (CASE INSTRUCTOR
    WHEN 1 THEN 'ALMA'
    WHEN 2 THEN 'CECILIA'
    WHEN 3 THEN 'BRUNO'
    WHEN 4 THEN 'DAVID'
    WHEN 5 THEN 'ESTELA'
    WHEN 6 THEN 'FERNANDO'
    ELSE 'INSTRUCTOR NO REGISTRADO'
    END) AS NOMBRE, NUM_TALLER FROM (
    SELECT INSTRUCTOR, COUNT(ID_TALLER) AS NUM_TALLER
    FROM TALLER
    WHERE INSTRUCTOR IS NOT NULL
    GROUP BY INSTRUCTOR
    ORDER BY NUM_TALLER DESC
) WHERE ROWNUM = 1;

//5. MOSTRAR TODOS LOS INSTRUCTORES Y LA CANTIDAD DE TALLERES QUE IMPARTEN
SELECT (CASE INSTRUCTOR
    WHEN 1 THEN 'ALMA'
    WHEN 2 THEN 'CECILIA'
    WHEN 3 THEN 'BRUNO'
    WHEN 4 THEN 'DAVID'
    WHEN 5 THEN 'ESTELA'
    WHEN 6 THEN 'FERNANDO'
    ELSE 'INSTRUCTOR NO REGISTRADO'
    END) AS NOMBRE , COUNT (ID_TALLER) AS NUM_TALLER FROM TALLER  GROUP BY INSTRUCTOR ORDER BY NUM_TALLER DESC;

//6. ORDENAR LOS TALLERES ALFABETICAMENTE POR TITULO Y LUEGO POR DURACION DE MAYOR A MENOR
SELECT * FROM TALLER ORDER BY TITULO ASC, DURACION_HR ASC;

//7. ORDENAR LOS PARTICIPANTES POR NOMBRE Y EDAD 
SELECT * FROM PARTICIPANTE ORDER BY NOMBRE ASC, EDAD ASC;

//8. MOSTRAR EL TOTAL DE HORAS QUE TOMARA CADA PARTICIPANTE SEGUN SU TALLER
SELECT NOMBRE,TITULO ,DURACION_HR FROM PARTICIPANTE P
INNER JOIN TALLER T
ON T.ID_TALLER=P.TALLER_ID ORDER BY DURACION_HR ASC;

//9. MOSTRAR EL PARTICIPANTE QUE NO TIENE TALLER ASIGNADO JUNTO CON SU CASE DE OCUPACION
SELECT ID_PARTICIPANTE, NOMBRE, APELLIDO, EDAD,OCUPACION,(
   CASE OCUPACION
    WHEN 1 THEN 'ESTUDIANTE'
    WHEN 2 THEN 'DOCENTE'
    WHEN 3 THEN 'EMPRENDEDOR'
    WHEN 4 THEN 'PROFESIONAL INDEPENDIENTE'
    WHEN 5 THEN 'EMPLEADO'
    ELSE 'OCUPACION NO REGISTRADA'
    END
    )AS OCUPACION_TXT, TALLER_ID  
    FROM PARTICIPANTE WHERE TALLER_ID IS NULL;

//10. MOSTRAR LOS TALLERES QUE NO HAN SIDO ASIGNADOS A NINGUN PARTICIPANTE Y SU CASE DE INSTRUCTOR Y DE NIVEL
SELECT ID_TALLER, TITULO, NIVEL,(
    CASE NIVEL
        WHEN 1 THEN 'BASICO'
        WHEN 2 THEN 'INTERMEDIO'
        WHEN 3 THEN 'AVANZADO'
        ELSE 'NO REGISTRADO'
     END
    )AS NIVEL_TXT, DURACION_HR,INSTRUCTOR,(
    CASE INSTRUCTOR
        WHEN 1 THEN 'ALMA'
        WHEN 2 THEN 'CECILIA'
        WHEN 3 THEN 'BRUNO'
        WHEN 4 THEN 'DAVID'
        WHEN 5 THEN 'ESTELA'
        WHEN 6 THEN 'FERNANDO'
        ELSE 'INSTRUCTOR NO REGISTRADO'
    END)AS INSTRUCTOR_TXT, ID_PARTICIPANTE
    FROM TALLER T
    LEFT JOIN PARTICIPANTE P
    ON T.ID_TALLER = P.TALLER_ID
    WHERE P.TALLER_ID IS NULL;

//11. MOSTRAR EL DETALLE DE CADA PARTICIPANTE CON LOS DATOS DEL TALLER AL QUE ASISTIRA USANDO CASE Y CONCAT O PIPE
//EJ: EL PARTICIPANTE: JORGE LUNA, DE 26 AÑOS Y QUE SE DEDICA A SER ESTUDIANTE TOMA EL TALLER DE ORATORIA QUE MPARTE EL INSTRUCTOR(A) ALMA EN EL NIVEL MEDIO CON UNA DURACION
//DE 10 HORAS
SELECT ('EL PARTICIPANTE: ' || NOMBRE || ' DE ' || EDAD || ' AÑOS Y QUE SE DEDICA A SER ' || (
    CASE OCUPACION
    WHEN 1 THEN 'ESTUDIANTE'
    WHEN 2 THEN 'DOCENTE'
    WHEN 3 THEN 'EMPRENDEDOR'
    WHEN 4 THEN 'PROFESIONAL INDEPENDIENTE'
    WHEN 5 THEN 'EMPLEADO'
    ELSE 'OCUPACION NO REGISTRADA'
    END    
) || ' TOMA EL ' || TITULO || ' QUE IMPARTE EL INSTRUCTOR(A) '|| (
    CASE INSTRUCTOR
        WHEN 1 THEN 'ALMA'
        WHEN 2 THEN 'CECILIA'
        WHEN 3 THEN 'BRUNO'
        WHEN 4 THEN 'DAVID'
        WHEN 5 THEN 'ESTELA'
        WHEN 6 THEN 'FERNANDO'
        ELSE 'INSTRUCTOR NO REGISTRADO'
    END) || ' EN EL NIVEL ' || (
    CASE NIVEL
        WHEN 1 THEN 'BASICO'
        WHEN 2 THEN 'INTERMEDIO'
        WHEN 3 THEN 'AVANZADO'
        ELSE 'NO REGISTRADO'
     END) || ' CON UNA DURACION DE ' || DURACION_HR || ' HORAS')AS INFORMACION_DETALLADA 
FROM PARTICIPANTE P
LEFT JOIN TALLER T
ON P.TALLER_ID = T.ID_TALLER;
