/*CASE
WHEN condicion1 THEN resultado1
WHEN condicion2 THEN resultado2
...
ELSE resultado_Predeterminado
END
*/
DROP TABLE LIBRO;

--CREAR ENTIDAD CON DDL LA ENTIDAD DE LIBRO
CREATE TABLE LIBROS(
    ID_LIBRO NUMBER,
    NOMBRE NVARCHAR2(100),
    AUTOR NVARCHAR2(100),
    GENERO NUMBER,--1. DRAMA, 2. TERROR, 3. CIENCIA FICCION, 4. NOVELA, 5. THRILLER, 6. COMEDIA
    NO_PAGINAS NUMBER,
    PRECIO NUMBER,
    EDITORIA NVARCHAR2(100),
    CONSTRAINT LIBROS_PK PRIMARY KEY(ID_LIBRO)
);

INSERT INTO LIBROS VALUES(1, 'LOS JUEGOS DEL HAMBRE', 'SUZZANE COLLINS', 3 , 600, 500, 'COMETA');
INSERT INTO LIBROS VALUES(2, 'FLORES EN EL ATICO', 'V. ANDREWS', 4 , 800, 640, 'DE BOLSILLO');
INSERT INTO LIBROS VALUES(3, 'CARRETERA MALDITA', 'NULL', NULL , NULL, 840, 'DE BOLSILLO');
INSERT INTO LIBROS VALUES(4, 'MIL BESOS TUYOS', 'TILLIE COLE', 1 , 500, 500, 'ROCA');
INSERT INTO LIBROS VALUES(5, 'THE MAZE RUNNER', 'JAMES DASHER', 3 , 700, 900, 'DELACORTE PRESS');
INSERT INTO LIBROS VALUES(6, 'MIL BESOS TUYOS', 'TILLIE COLE', 1 , 500, 500, 'ROCA');
INSERT INTO LIBROS VALUES(7, 'THE MAZE RUNNER', 'JAMES DASHER', 3 , 700, 900, 'DELACORTE PRESS');
INSERT INTO LIBROS VALUES(8, 'MIL BESOS TUYOS', 'TILLIE COLE', 1 , 500, 500, 'ROCA');
INSERT INTO LIBROS VALUES(9, 'THE MAZE RUNNER', 'JAMES DASHER', 3 , 700, 900, 'DELACORTE PRESS');
COMMIT;

SELECT * FROM libro;


//PRIMERA FORMA DEL CASE
SELECT ID_LIBRO,NOMBRE,AUTOR,(
    CASE GENERO
    WHEN 1 THEN 'DRAMA'
    WHEN 2 THEN 'TERROR'
    WHEN 3 THEN 'CIENCIA FICCION'
    WHEN 4 THEN 'NOVELA'
    WHEN 5 THEN 'THRILLER'
    WHEN 6 THEN 'COMEDIA'
    ELSE 'SIN GENERO'
    END
) AS GENERO_TEXTO, NO_PAGINAS, PRECIO, EDITORIA FROM LIBRO;

//SEGUNDA FORMA DEL CASE
SELECT ID_LIBRO, NOMBRE,GENERO, NO_PAGINAS,(
    CASE
    WHEN PRECIO > 400 THEN 'ES CARO: ' || TO_CHAR(PRECIO, '$999.00') || ' PESOS'
    WHEN PRECIO <= 400 THEN 'ES BARATO: ' || TO_CHAR(PRECIO, '$999.00') || ' PESOS'
    ELSE 'PRECIO NO DEFINIDO'
    END
)AS PRECIO, EDITORIA FROM LIBRO;

