//Parte 5: Actividades Avanzadas (Funciones, Paquetes y Cursores)

//Actividad 1: Función que devuelve el nombre del proyecto más largo
//A Crea una función que devuelva el nombre del proyecto con mayor duración en días (fecha_fin - fecha_inicio).
CREATE OR REPLACE FUNCTION FN_DURACION_PROYECTO
RETURN NVARCHAR2
IS
    LV_NOMBRE PROYECTO.NOMBRE%TYPE;
    LV_TOTAL_DIAS NUMBER;
BEGIN
    
    SELECT NOMBRE, (FECHA_FIN - FECHA_INICIO) INTO LV_NOMBRE, LV_TOTAL_DIAS FROM PROYECTO
    WHERE (FECHA_FIN - FECHA_INICIO) = (SELECT MAX(FECHA_FIN - FECHA_INICIO) FROM PROYECTO)
    AND ROWNUM = 1; 
    
    RETURN 'EL PROYECTO CON MAS DURACION ES EL: ' || LV_NOMBRE || ' CON UN TOTAL DE: ' || LV_TOTAL_DIAS || ' DIAS DE TRABAJO';
END FN_DURACION_PROYECTO;
/

SELECT FN_DURACION_PROYECTO FROM DUAL;


//Actividad 2: Función que clasifica un proyecto
//Crea una función que reciba un ID_PROYECTO y devuelva un mensaje como:
//'Corto' si dura menos de 30 días.
//'Mediano' entre 30 y 90 días.
//'Largo' si dura más de 90 días.

CREATE OR REPLACE FUNCTION FN_CLASIFICACION_PROYECTO_DURACION (P_ID_PROYECTO NUMBER)
RETURN NVARCHAR2
IS
    LV_NOMBRE NVARCHAR2(100);
    LV_DURACION NUMBER;
    LV_RESULTADO NVARCHAR2(100);

BEGIN
    SELECT NOMBRE, NVL((FECHA_FIN - FECHA_INICIO),0) INTO LV_NOMBRE, LV_DURACION FROM PROYECTO WHERE ID_PROYECTO = P_ID_PROYECTO;
    IF LV_DURACION BETWEEN 30 AND 90 THEN
        LV_RESULTADO := 'MEDIANA';
    ELSIF LV_DURACION < 30 THEN 
        LV_RESULTADO := 'CORTA';
    ELSE
        LV_RESULTADO := 'LARGA';
    END IF;
    
    RETURN 'EL PROYECTO: ' || LV_NOMBRE || ', TIENE UNA DURACION ' || LV_RESULTADO || '('||LV_DURACION||' DIAS)' ;
END FN_CLASIFICACION_PROYECTO_DURACION;
/

SELECT FN_CLASIFICACION_PROYECTO_DURACION(1) FROM DUAL;
