//PARTE 4. EJERCICIO DE APLICACION
//1. ESCRIBE UN PROCEDIMIENTO PL/SQL QUE:
//CALCULE EL TOTAL DE HORAS TRABAJADAS POR CADA TRABAJADOR
//ACTUALICE LA TABLA EMPLEADO CON UN NUEVO CAMPO TOTAL_HORAS QUE ALMACENE ESE TOTAL
//IMPRIMA UN MENSAJE POR CADA EMPLEADO INDICANDO LA HORA TOTAL TRABAJADA

ALTER TABLE EMPLEADO ADD TOTAL_HORAS NUMBER;
SELECT * FROM EMPLEADO;

CREATE OR REPLACE PROCEDURE PR_TOTAL_HORAS
IS
    V_TOTAL_HORAS NUMBER := 0;
BEGIN
    DBMS_OUTPUT.PUT_LINE('<<<<<<<<<<<<<<HORAS TRABAJADAS>>>>>>>>>>>>>>>>>>');
    
    FOR EMP IN (SELECT ID_EMPLEADO, NOMBRE FROM EMPLEADO ORDER BY NOMBRE) LOOP
        --CALCULAR HORAS TRABAJADAS
        SELECT NVL(SUM(HORAS_TRABAJADAS), 0) 
        INTO V_TOTAL_HORAS
        FROM ASIGNACION
        WHERE EMPLEADO_ID = emp.ID_EMPLEADO;
        
        --ACTUALIZACION DE COLUMNA HORAS
        UPDATE EMPLEADO SET TOTAL_HORAS = V_TOTAL_HORAS
        WHERE ID_EMPLEADO = emp.ID_EMPLEADO;
        
        DBMS_OUTPUT.PUT_LINE('EMPLEADO: ' || EMP.NOMBRE ||  ' TRABAJA UN TOTAL DE: ' ||V_TOTAL_HORAS || ' HORAS');
        
    END LOOP;
END PR_TOTAL_HORAS;
/

EXEC PR_TOTAL_HORAS;

SELECT * FROM EMPLEADO;