//Actividad 5: Uso de cursores implícitos
//Crea un procedimiento que:
//Inserte una nueva asignación para un empleado.
//Verifique con SQL%ROWCOUNT si se insertó correctamente.
//Imprima un mensaje dependiendo del resultado.

CREATE OR REPLACE PROCEDURE PR_INSERTAR_ASIGNACION (P_ID_ASIGNACION IN NUMBER,P_EMPLEADO_ID IN NUMBER, P_PROYECTO_ID IN NUMBER,P_HORAS_TRABAJADAS IN NUMBER)
IS
BEGIN
    INSERT INTO ASIGNACION VALUES (P_ID_ASIGNACION, P_EMPLEADO_ID, P_PROYECTO_ID, P_HORAS_TRABAJADAS);
    
    IF SQL%ROWCOUNT = 1 THEN
        DBMS_OUTPUT.PUT_LINE('PROYECTO ASIGNADO EXITOSAMENTE AL EMPLEADO: ' || P_EMPLEADO_ID);
    ELSE
        DBMS_OUTPUT.PUT_LINE('ERROR AL ASIGNAR PROYECTO');
        ROLLBACK;
    END IF;
END PR_INSERTAR_ASIGNACION;
/

BEGIN
    PR_INSERTAR_ASIGNACION(12, 3,7, 90);
END;
/


SELECT * FROM ASIGNACION;