//Actividad 7: Paquete con funciones reutilizables
//Crea un paquete PKG_PROYECTOS que incluya:
//Una función que devuelve el total de horas de un empleado en un proyecto específico.
//Un procedimiento que recorra todos los proyectos de un empleado y utilice la función anterior para imprimir cada uno con sus horas trabajadas.
CREATE OR REPLACE PACKAGE PKG_PROYECTOS AS
    FUNCTION FN_HORAS_PROYECTO(P_ID_EMPLEADO IN NUMBER,P_ID_PROYECTO IN NUMBER) RETURN NUMBER;
    
    PROCEDURE PR_REPORTE_EMPLEADOS(P_ID_EMPLEADO IN NUMBER);
END PKG_PROYECTOS;
/


CREATE OR REPLACE PACKAGE BODY PKG_PROYECTOS AS
   FUNCTION FN_HORAS_PROYECTO(P_ID_EMPLEADO IN NUMBER,P_ID_PROYECTO IN NUMBER) RETURN NUMBER 
    IS
        V_TOTAL_HORAS NUMBER:=0;
    BEGIN
        SELECT NVL(SUM(HORAS_TRABAJADAS), 0) INTO V_TOTAL_HORAS FROM ASIGNACION
        WHERE EMPLEADO_ID = P_ID_EMPLEADO
        AND PROYECTO_ID = P_ID_PROYECTO;
        
        RETURN V_TOTAL_HORAS;
    END FN_HORAS_PROYECTO;


    PROCEDURE PR_REPORTE_EMPLEADOS(P_ID_EMPLEADO IN NUMBER) IS
        LV_TOTAL_HORAS NUMBER :=0;
    BEGIN
        DBMS_OUTPUT.PUT_LINE('<<<<<<<<<<<<<<<REPORTE DE EMPLEADOS>>>>>>>>>>>');
        FOR A IN (SELECT PROYECTO_ID FROM ASIGNACION WHERE EMPLEADO_ID = P_ID_EMPLEADO) LOOP
            DBMS_OUTPUT.PUT_LINE('EL EMPLEADO CON ID: ' ||  P_ID_EMPLEADO || ' TRABAJA EN EL PROYECTO CON ID:' || A.PROYECTO_ID || ' UN TOTAL DE ' || FN_HORAS_PROYECTO(P_ID_EMPLEADO, A.PROYECTO_ID) || ' HORAS');
            LV_TOTAL_HORAS := LV_TOTAL_HORAS + FN_HORAS_PROYECTO(P_ID_EMPLEADO, A.PROYECTO_ID);
        END LOOP;
        DBMS_OUTPUT.PUT_LINE('EL EMPLEADO TRABAJO UN TOTAL DE: ' || LV_TOTAL_HORAS);
    END PR_REPORTE_EMPLEADOS;
END PKG_PROYECTOS;
/

BEGIN
    PKG_PROYECTOS.PR_REPORTE_EMPLEADOS(3);
END;
/
