//PARTE 4. EJERCICIO DE APLICACION
//1. ESCRIBE UN PROCEDIMIENTO PL/SQL QUE:
//CALCULE EL TOTAL DE HORAS TRABAJADAS POR CADA TRABAJADOR
//ACTUALICE LA TABLA EMPLEADO CON UN NUEVO CAMPO TOTAL_HORAS QUE ALMACENE ESE TOTAL
//IMPRIMA UN MENSAJE POR CADA EMPLEADO INDICANDO LA HORA TOTAL TRABAJADA

ALTER TABLE EMPLEADO ADD TOTAL_HORAS NUMBER;
SELECT * FROM EMPLEADO;

CREATE OR REPLACE PROCEDURE PR_TOTAL_HORAS
IS
    V_TOTAL_HORAS NUMBER := 0;
BEGIN
    DBMS_OUTPUT.PUT_LINE('<<<<<<<<<<<<<<HORAS TRABAJADAS>>>>>>>>>>>>>>>>>>');
    
    FOR EMP IN (SELECT ID_EMPLEADO, NOMBRE FROM EMPLEADO ORDER BY NOMBRE) 
        LOOP
        --CALCULAR HORAS TRABAJADAS
        SELECT NVL(SUM(HORAS_TRABAJADAS), 0) 
        INTO V_TOTAL_HORAS
        FROM ASIGNACION
        WHERE EMPLEADO_ID = EMP.ID_EMPLEADO;
        
        --ACTUALIZACION DE COLUMNA HORAS
        UPDATE EMPLEADO SET TOTAL_HORAS = V_TOTAL_HORAS
        WHERE ID_EMPLEADO = EMP.ID_EMPLEADO;
        
        DBMS_OUTPUT.PUT_LINE('EMPLEADO: ' || EMP.NOMBRE ||  ' TRABAJA UN TOTAL DE: ' ||V_TOTAL_HORAS || ' HORAS');
        
    END LOOP;
END PR_TOTAL_HORAS;
/

EXEC PR_TOTAL_HORAS;

SELECT * FROM EMPLEADO;
SELECT * FROM ASIGNACION;

//7. Crear y Consultar una Vista
//Crear la Vista: Escribe una vista que muestre la información de los empleados junto con el nombre de su departamento y el total de horas trabajadas en todos los proyectos. La vista debe incluir los siguientes campos:
//ID_EMPLEADO
//NOMBRE_EMPLEADO
//DEPARTAMENTO
//TOTAL_HORAS_TRABAJADAS
//La vista debe obtener la información combinando las tablas EMPLEADO, DEPARTAMENTO y ASIGNACION.


CREATE OR REPLACE VIEW V_DETALLE_EMPLEADO
AS 
SELECT E.ID_EMPLEADO, E.NOMBRE, D.NOMBRE AS DEPARTAMENTO, NVL(SUM(A.HORAS_TRABAJADAS), 0) AS TOTAL_HORAS_TRABAJADAS FROM EMPLEADO E
INNER JOIN DEPARTAMENTO D
ON E.DEPARTAMENTO_ID = D.ID_DEPARTAMENTO
LEFT JOIN ASIGNACION A
ON A.EMPLEADO_ID = E.ID_EMPLEADO
GROUP BY E.ID_EMPLEADO, E.NOMBRE, D.NOMBRE
ORDER BY E.ID_EMPLEADO;

SELECT * FROM V_DETALLE_EMPLEADO;
SELECT * FROM ASIGNACION;

//Consultar la Vista: Escribe una consulta para la vista creada en el paso anterior. La consulta debe mostrar:
//Todos los empleados con un TOTAL_HORAS_TRABAJADAS mayor a 100.
SELECT * FROM V_DETALLE_EMPLEADO WHERE TOTAL_HORAS_TRABAJADAS > 100;

//Los empleados cuyo nombre contenga la letra "A".
SELECT * FROM V_DETALLE_EMPLEADO WHERE UPPER(NOMBRE) LIKE'%A%';