//Actividad 4: Paquete EMPLEADO_UTILS
//Declara un paquete con:
//Una función FN_CLASIFICAR_SALARIO que reciba un salario y retorne 'ALTO', 'MEDIO', 'BAJO'.
//Un procedimiento PR_REPORTE_EMPLEADOS que imprima ID, nombre y salario clasificado de todos los empleados.
//Un cursor declarado en el paquete para recorrer los empleados.

CREATE OR REPLACE PACKAGE PKG_GESTION_EMPLEADOS AS
    FUNCTION FN_CLASIFICAR_SALARIO(P_SALARIO IN NUMBER) RETURN NVARCHAR2;
    
    PROCEDURE PR_REPORTE_EMPLEADOS;
    
    CURSOR CURSOR_EMPLEADO IS
        SELECT ID_EMPLEADO, NOMBRE, SALARIO
        FROM EMPLEADO
        ORDER BY NOMBRE;
END PKG_GESTION_EMPLEADOS;
/

CREATE OR REPLACE PACKAGE BODY PKG_GESTION_EMPLEADOS AS
    FUNCTION FN_CLASIFICAR_SALARIO(P_SALARIO NUMBER) 
    RETURN VARCHAR2 
    IS
    BEGIN
        RETURN CASE
            WHEN P_SALARIO > 3000 THEN 'ALTO'
            WHEN P_SALARIO BETWEEN 2000 AND 3000 THEN 'MEDIO'
            ELSE 'BAJO'
        END;
    END FN_CLASIFICAR_SALARIO;
    
    PROCEDURE PR_REPORTE_EMPLEADOS IS
    BEGIN
        DBMS_OUTPUT.PUT_LINE('<<<<<<<<<<<<<<<REPORTE DE EMPLEADOS>>>>>>>>>>>');
        FOR EMP IN CURSOR_EMPLEADO LOOP
            DBMS_OUTPUT.PUT_LINE('ID: ' || EMP.ID_EMPLEADO || ' DE NOMBRE: ' || EMP.NOMBRE || ' CON UN SALARIO $' || EMP.SALARIO || '(' || FN_CLASIFICAR_SALARIO(EMP.SALARIO) || ')');
        END LOOP;
    END PR_REPORTE_EMPLEADOS;
END PKG_GESTION_EMPLEADOS;
/

SELECT 
    NOMBRE, 
    SALARIO, 
    PKG_GESTION_EMPLEADOS.FN_CLASIFICAR_SALARIO(SALARIO) AS CATEGORIA
FROM EMPLEADO;

BEGIN
    PKG_GESTION_EMPLEADOS.PR_REPORTE_EMPLEADOS;
END;
/

SELECT * FROM EMPLEADO;