--FUNCIONES PL/SQL (FUNCTION):
-- ES UN BLOQUE DE CODIGO QUE RETORNA UN VALOR

--CRAR UNA FUNCION PARA DETERMINAR SI UN NUMERO ES PAR
CREATE OR REPLACE FUNCTION FN_NUMERO_PAR(P_NUMERO IN NUMBER)
RETURN NVARCHAR2
IS
    LV_RESULTADO NVARCHAR2(100);
BEGIN
    --INSTRUCCIONES
    --EL PARAMETRO ES DIVISIBLE ENTRE 2:
    IF MOD(P_NUMERO,2)=0
        THEN
            LV_RESULTADO := 'EL NUMERO ' || P_NUMERO ||' ES PAR';
        ELSE
            LV_RESULTADO := 'EL NUMERO ' || P_NUMERO ||' NO ES PAR';
    END IF;
    RETURN LV_RESULTADO;
END FN_NUMERO_PAR;
/

--FORMAS DE INVOCAR UNA FUNCION

--INVOCAR LA FUNCION CON UN BLOQUE ANONIMO
BEGIN
    DBMS_OUTPUT.PUT_LINE(FN_NUMERO_PAR(10));
END;
/

--POR MEDIO DE SENTENCIAS Y LA TABLA VIRTUAL
SELECT FN_NUMERO_PAR(21) FROM DUAL;



