//EJERCICIO DE PRACTICA DE VISTAS O VIEWS

--TRABAJAR SOBRE EL EJRCICIO LIBRO/AUTOR
//AGREGAR UNA NUEVA TABLA QUE SERA VENTA (ID_VENTA, LIBRO_ID,FECHA_VENTA,CANTIDAD)
CREATE TABLE VENTA(
    ID_VENTA NUMBER,
    LIBRO_ID NUMBER,
    FECHA_VENTA DATE,
    CANTIDAD NUMBER,
    CONSTRAINT VENTA_PK PRIMARY KEY (ID_VENTA),
    CONSTRAINT LIBRO_FK FOREIGN KEY (LIBRO_ID) REFERENCES LIBRO
);

//INSERCION DE VENTAS
INSERT INTO VENTA VALUES(1, 2, TO_DATE('2023-03-17','YYYY-MM-DD'), 4);
INSERT INTO VENTA VALUES(2, 1, TO_DATE('2024-02-21','YYYY-MM-DD'), 1);
INSERT INTO VENTA VALUES(3, 4, TO_DATE('2025-09-11','YYYY-MM-DD'), 2);
INSERT INTO VENTA VALUES(4, 3, TO_DATE('2022-12-10','YYYY-MM-DD'), 9);
INSERT INTO VENTA VALUES(5, 2, TO_DATE('2023-03-17','YYYY-MM-DD'), 4);
INSERT INTO VENTA VALUES(6, 1, TO_DATE('2024-02-21','YYYY-MM-DD'), 1);
INSERT INTO VENTA VALUES(7, 4, TO_DATE('2025-09-11','YYYY-MM-DD'), 2);
INSERT INTO VENTA VALUES(8, 3, TO_DATE('2022-12-10','YYYY-MM-DD'), 9);



//1.CREAR UNA VISTA QUE MUESTRE EL TITULO DEL LIBRO, NOMBRE DEL AUTOR Y SU PRECIO
CREATE OR REPLACE VIEW V_DETALLE_LIBRO_AUTOR
AS
SELECT L.TITULO, A.NOMBRE, L.PRECIO 
FROM LIBRO L
INNER JOIN AUTOR A
ON L.ID_AUTOR = A.ID_AUTOR;

SELECT * FROM V_DETALLE_LIBRO_AUTOR;

//2. CREAR UNA VISTA DE LIBROS CAROS, MOSTRAR LOS LIBROS MAYORES A 300
CREATE OR REPLACE VIEW V_LIBROS_CAROS
AS
SELECT * FROM LIBRO WHERE PRECIO > 300;

SELECT * FROM V_LIBROS_CAROS;


//3. CREAR UNA VISTA QUE CALCULE LA CANTIDAD TOTAL VENDIDA POR LIBRO
CREATE OR REPLACE VIEW V_VENTA_LIBROS
AS
SELECT TITULO, SUM(CANTIDAD) AS CANTIDAD_DE_LIBROS 
FROM LIBRO L
INNER JOIN VENTA V
ON V.LIBRO_ID = L.ID_LIBRO
GROUP BY TITULO;

SELECT * FROM V_VENTA_LIBROS;


//4. CREAR UNA VISTA QUE MUESTRE EL DETALLE DE VENTAS, LA FECHA, TITULO VENDIDO Y LA CANTIDAD VENDIDA
CREATE OR REPLACE VIEW V_DETALLE_VENTA
AS
SELECT V.FECHA_VENTA, L.TITULO, V.CANTIDAD
FROM LIBRO L
INNER JOIN VENTA V
ON V.LIBRO_ID = L.ID_LIBRO;

SELECT * FROM V_DETALLE_VENTA;
