--CURSORES
DROP TABLE LIBRO;
SELECT * FROM LIBROS;


CREATE OR REPLACE PROCEDURE PR_DETALLE_LIBRO IS
    CURSOR LIBRO_INFO IS
        SELECT NOMBRE,
            (CASE GENERO
                WHEN 1 THEN 'DRAMA'
                WHEN 2 THEN 'TERROR'
                WHEN 3 THEN 'CIENCIA FICCION'
                WHEN 4 THEN 'NOVELA'
                WHEN 5 THEN 'THRILLER'
                WHEN 6 THEN 'COMEDIA'
                ELSE 'SIN GENERO'
            END) AS GENERO, PRECIO FROM LIBROS;
        
        --VARIABLES LOCALES
        LV_NOMBRE LIBROS.NOMBRE%TYPE;
        LV_GENERO NVARCHAR2(20);
        LV_PRECIO NUMBER;
BEGIN
    --ABRIR EL CURSOR
    OPEN LIBRO_INFO;
    --RECUPERAR EL CURSOSR Y MOSTRAR DATOS CON UN LOOP
    LOOP
        --POR CADA FILA RECORRIDA SE TOMAN LOS DATOS DEL CURSOR
        FETCH LIBRO_INFO INTO LV_NOMBRE, LV_GENERO, LV_PRECIO;
        
        --CONDICION PARA SALIRSE CUANDDO EL CURSOSRYA NO TENGA DATOS
        EXIT WHEN LIBRO_INFO%NOTFOUND;
        
        --MOSTRASR LOS DATOS DEL CURSOR
        DBMS_OUTPUT.PUT_LINE('NOMBRE DEL LIBRO: ' || LV_NOMBRE || ' DE GENERO: ' || LV_GENERO || ' TIENE UN VALOR DE: $' || LV_PRECIO );
    END LOOP;
    CLOSE LIBRO_INFO;
END PR_DETALLE_LIBRO;
/

//EJECUTAR CON BLOQUE ANONIMO
BEGIN
    PR_DETALLE_LIBRO;   
END;
/

