--PROCEDIMIENTO ALMACENADO (SORE PROCEDURE)

SELECT * FROM COMPUTADORA;
DELETE FROM COMPUTADORA;

--CREAR UN DDL
CREATE TABLE COMPUTADORA_PRD(
    ID_COMPU NUMBER,
    MARCA NVARCHAR2(100),
    MODELO NVARCHAR2(100),
    RAM NUMBER,
    PROCESADOR NVARCHAR2(100),
    PRECIO NUMBER,
    CONSTRAINT COMPU_PRD_PK PRIMARY KEY (ID_COMPU)
);

INSERT INTO COMPUTADORA VALUES (1, 'ASUS', 'ROG STRIX', 16, 'INTEL Core i7 12th', 5000);
INSERT INTO COMPUTADORA VALUES (2, 'HP', 'OMEN 15', 32, 'AMD Ryzen 9 5900HX', 7500);
INSERT INTO COMPUTADORA VALUES (3, 'DELL', 'XPS 15', 64, 'INTEL Core i9 13th', 12000);
INSERT INTO COMPUTADORA VALUES (4, 'LENOVO', 'IDEA PAD', 8, 'AMD RYZEN 7', 13500);
INSERT INTO COMPUTADORA  VALUES (5, 'Lenovo', 'Legion 5', 16, 'Intel Core i7 11th', 16000);
INSERT INTO COMPUTADORA  VALUES (6, 'Lenovo', 'Legion 5', 16, 'Intel Core i7 11th', 16000);
COMMIT;

--SENTENCIA INSERT INTO SELECT
--PROCEDIMIENTO ALMACENADO

CREATE OR REPLACE PROCEDURE PR_RESPALDO_COMPUTADORA
IS
    --DELCARACION DE VARIABLES
BEGIN
    --INSTRUCCIONES A EJECUTAR
    --ELIMINAR TODA MI TABLA COMPUTADORA_PRD
    --DML
    DELETE FROM COMPUTADORA_PRD; --LIMPIAR LA TABLA YA QUE LO QUE HACER ES RELEER LA TABLA COMPUTADORA POR COMPLETO PARA ALMACENAR SUS DATOS
                                -- SI NO SE LIMPIA, HABRA DATOS DUPLICADOS CADA VEZ QUE SE EJECUTE O MANDARA ERROR YA QUE ANALIZARA DESDE EL INDICE 1
    INSERT INTO COMPUTADORA_PRD(ID_COMPU, MARCA, MODELO, RAM, PROCESADOR, PRECIO)
    SELECT ID_COMPU, MARCA, MODELO, RAM, PROCESADOR, PRECIO FROM COMPUTADORA;
END PR_RESPALDO_COMPUTADORA;
/

--EJECUTAR EL PROCEDIMIENTO ALMACENADO
EXECUTE PR_RESPALDO_COMPUTADORA;

DELETE FROM COMPUTADORA WHERE ID_COMPU=6;
SELECT * FROM COMPUTADORA;
SELECT * FROM COMPUTADORA_PRD;