--VISTAS O VIEWS

SELECT * FROM PADRE;
SELECT * FROM HIJO;

//CREACION DE VISTAS
CREATE OR REPLACE VIEW V_PADRE_HIJO_DETALLE
AS
SELECT H.ID_HIJO,  H.NOMBRE, H.APELLIDO, H.EDAD, NVL(H.HOBBIE, 'SIN HOBIE') AS HOBBIE, NVL(H.PADRE_ID, 0) AS PADRE FROM HIJO H
LEFT JOIN PADRE P
ON P.ID_PADRE = H.PADRE_ID;

//VIZUALIZAR TABLA
SELECT * FROM V_PADRE_HIJO_DETALLE;


