--CREAR UNA TABLA PARA ENTIDAD AUTOMOVIL
CREATE TABLE AUTOMOVIL(
    ID_AUTO NUMBER,
    MARCA NVARCHAR2(100),
    SUB_MARCA NVARCHAR2(100),
    MODELO NUMBER,
    COLOR NVARCHAR2(100),
    PRECIO NUMBER,
    VERSION NVARCHAR2(100),
   CONSTRAINT AUTO_PK PRIMARY KEY (ID_AUTO)
);

INSERT INTO AUTOMOVIL VALUES(1, 'NISSAN', 'SENTRA' , 2001, 'GRIS', 80000, 'AUSTERO');
INSERT INTO AUTOMOVIL VALUES(2, 'TOYOTA', 'CHEYENNE', 2007, 'NEGRA', 150000, 'DE LUJO');
INSERT INTO AUTOMOVIL VALUES(3, 'TOYOTA', 'TACOMA' , 2020, 'BLANCO', 1200000, 'TRX');
INSERT INTO AUTOMOVIL VALUES(4, 'NISSAN', 'Z' , 2018, 'NEGRO', 300000, '370');
INSERT INTO AUTOMOVIL VALUES(5, 'FORD', 'FOCUS', 2012, 'AZUL', 110000, 'SE');
INSERT INTO AUTOMOVIL VALUES(6, 'CHEVROLET', 'CRUZE', 2014, 'ROJO', 115000, 'LT');
INSERT INTO AUTOMOVIL VALUES(7, 'MAZDA', 'MAZDA3', 2012,'BLANCO', 200000, 'DE LUJO');
INSERT INTO AUTOMOVIL VALUES(8, 'KIA', 'FORTE', 2020,'AZUL', 250000, 'DE LUJO');

/*
REALIZAR LAS SIGUENTES SENTENCIAS

1. MOSTRAR LA INFORMACION ORDENADA DE LOS AUTOS DE ACUERDO A SU PRECION DE MAYOR A MENOR
    ADEMAS DE AGREGARLE EL SIGNO DE PESO EN EL PRECIO Y SEPARAR POR COMILLAS LOS MILES CON 2 DECIMALES EJ: $400,000.00 
2. BUSCAR AUTOS QUE EN LA SUBMARCA CONTENGAN UNA LETRA 'E' Y SACAR EL PROMEDIO DE SU PRECIO. APLICAR FORMATO 
3. MOSTRAR LOS AUTOS QUE CUESTAN 700,000 O MAS Y CAMBIAR LAS LETRAS A MINUSCULAS DE LA MARCA Y SUBMARCA.
4. CONSULTAR LOS REGISTROS QUE NO SEAN NULOS EN LA VERSION QUE SU PRECIO SEA MAYOR A 500MIL Y ORDENAR DE MENOR A MAYOR
5. MOSTRAR LOS AUTOMOVILES QUE SE PRECIO SEA MAYOR A 550 MIL PERO MENOR A 800MIL
6. BUSCAR LOS AUTOMOVILES QUE SEAN DE COLOR NEGRO Y AGERAGR FORMATO EN EL PRECIO Y LA PALABRA PESOS AL FINAL EJ: $400,000.00 PESOS
7. CONTAR CUANTOS AUTOS TENGO DE CADA MARCA E INDICAR LA MARCA QUE PERTENECE CADA CONTEO
8. MOSTRAR EL REGISTRO QUE TENGA EL PRECIO MAS ALTO 
*/

//1. MOSTRAR INFORMACION ORDENADAD DE LOS AUTOS DE ACUERDO A SU PRECIO CON FORMATO DE MAYOR A MENOR 
SELECT ID_AUTO, MARCA,SUB_MARCA,MODELO,COLOR, TO_CHAR(PRECIO, '$999,999,990.00')AS precio_formateado, VERSION FROM AUTOMOVIL;


//2. BUSCAR AUTOS QUE CONTENGAN LA LETRA E Y SACAR PROMEDIO DE PRECIO
SELECT TO_CHAR(AVG(PRECIO), '$999,999,990.00') AS PRECIO_PROMEDIO FROM AUTOMOVIL WHERE SUB_MARCA LIKE '%E%' AND SUB_MARCA LIKE '%E';

//3. AUTOS QUE CUESTEN 700MIL O MAS Y CAMBIAR LAS LETRAS DE A MINUSCULAS DE LA MARCA Y SUBMACA
SELECT LOWER(MARCA) AS MARCA_MIN, LOWER(SUB_MARCA) AS SUB_MARCA_MIN FROM AUTOMOVIL WHERE PRECIO > 700000;

//4. CONSULTAR LOS REGISTROS QUE NO SEAN NULOS EN LA VERSION, QUE SU PRECIO SEA MAYOR A 500 MILY ORDENAR DE MENOR A MAYOR
SELECT * FROM AUTOMOVIL WHERE VERSION IS NOT NULL AND PRECIO > 500000 ORDER BY PRECIO ASC;

//5. MOSTRAR AUTOMOVII CON PRECIO MAYOR A 550 MIL PERO MENOS DE 800MIL
SELECT * FROM AUTOMOVIL WHERE PRECIO > 500000 AND PRECIO < 800000;

//6. BUSCAR AUTOMOVIL DE COLOR NEGRO Y AGREGAR FORMATO EN EL PRECIO Y LAPALABRA PESOS AL FINAL 
SELECT ID_AUTO, MARCA,SUB_MARCA,MODELO,COLOR, TO_CHAR(precio, '$999,999,990.00') || ' PESOS' AS precio_formateado, VERSION FROM AUTOMOVIL WHERE COLOR LIKE'NEGRO';

//7. CONTAR CUANOS AUTOS HAY DE CADA MARCA E INDICAR LA MARCA QUE PERTEMECE
SELECT MARCA, COUNT (ID_AUTO) AS NO_DE_AUTOS FROM automovil GROUP BY MARCA;

//8. MOSTRAR REGISTRO QUE TENGA EL PRECIO MAS ALTO Y DAR FORMATO AL PRECIO
SELECT ID_AUTO, MARCA,SUB_MARCA,MODELO,COLOR, TO_CHAR(PRECIO, '$999,999,990.00') AS precio_formateado, VERSION FROM AUTOMOVIL WHERE PRECIO=(
    SELECT MAX(PRECIO) FROM AUTOMOVIL
);

//9. MOSTRAR AUTO MAS ANTIGUO Y FORMATEAR EL PRECIO ADEMAS DE AGREGARLE AÑO AL MODELO 
SELECT ID_AUTO, MARCA,SUB_MARCA,'AÑO ' || MODELO AS MODELO_CON_AÑO,COLOR, TO_CHAR(PRECIO, '$999,999,990.00') AS precio_formateado, VERSION FROM AUTOMOVIL WHERE MODELO=(
    SELECT MIN(MODELO) FROM AUTOMOVIL
);

//10. DESGLOSAR DETALLE DE LOS AUTOS
SELECT 'EL AUTO ' || SUB_MARCA || ' DE MARCA ' || MARCA || 'ES UN MODELO ' || MODELO || ' EN COLOR ' || COLOR || ' Y VERSION ' || VERSION || ' Y TIENE UN VALOR DE ' || TO_CHAR(PRECIO, '$999,999,990.00') AS DETALLES FROM AUTOMOVIL;