--USO DE DML Para insertar valores en la tabla de Empleado.

INSERT INTO empleado VALUES(1,'Mauricio', 'Sanchez', 26,'Abogado','Departamento Penal');
INSERT INTO empleado VALUES(2,'Liliana', 'Zamora', 24,'Auxiliar','RH');
INSERT INTO empleado VALUES(3,'Vania', 'Huerta', 25,'Auxiliar','Sistemas');
INSERT INTO empleado VALUES(4,'Jaqueline', 'Matus', 23,'Asistente','Contabilidad');
INSERT INTO empleado VALUES(5,'Mario', 'Lopez', 22,'Programador','Contabilidad');
INSERT INTO empleado VALUES(6,'Jesus', 'Santiago', 34,'Doctor','Contabilidad');
INSERT INTO empleado VALUES(7,'Carlos', 'Jimenez', 28,'Auxiliar','Administrativo');
INSERT INTO empleado VALUES(8,'Ana', 'Conrado', 26,'Soporte','TI');

COMMIT;
SELECT * FROM empleado;
DELETE FROM EMPLEADO;

--FUNCIONES

--MODIFICAR O CAMBIAR NOMBRE DE COLUMAS
ALTER TABLE EMPLEADO RENAME COLUMN APP TO Apellido;

--Actualizar Informacion con DML:
UPDATE empleado SET NOMNRE = 'Lili' WHERE ID_EMPLEADO=2;


--Funciones de orden
SELECT * FROM EMPLEADO ORDER BY EDAD ASC;
SELECT * FROM EMPLEADO ORDER BY EDAD DESC;

--BUSQUEDA DE INFORMACION CON CARACTERES EN ESPECIFICO
-- BUSCAR EMPLEADO QUE SU NOMBRE EMPIECE CON LA LETRA A

SELECT * FROM EMPLEADO WHERE NOMNRE LIKE 'A%';

--BUSCAR EMPLEADO QUE SU NOMBRE TENGA UNA LETRA I
SELECT * FROM EMPLEADO WHERE NOMNRE LIKE '%i%';

--BUSCAR EMPLEADO QUE SU NOMBRE TERMINE CON LA LETRA S
SELECT * FROM EMPLEADO WHERE NOMNRE LIKE '%s';

--BUSCAR EMPLEADO QUE SU NOMBRE SEA NULL
SELECT * FROM EMPLEADO WHERE NOMNRE IS NOT NULL;

--USO DE LA TABLA DUAL 
SELECT 5+5 AS SUMA FROM DUAL;

--USO DE LA FUNCION LENGHT
SELECT LENGTH ('ESTA ES UNA CADENA DE PRUEBA DEL METODO LENGTH') AS TAMANIO FROM DUAL;

--BUSQUEDA CON CONDICIONES

--BUSCAR EMPLEADO QUE SEA MAYOR DE 25 ANIOS
SELECT * FROM EMPLEADO WHERE EDAD > 25;

--BUSCAR EMPLEADOS MENORES DE 26
SELECT * FROM EMPLEADO WHERE EDAD < 26;

--BUSCAR EMPLEADOS QUE SEAN MAYORES DE 24 Y MENORES DE 28
SELECT * FROM EMPLEADO WHERE EDAD > 24 AND EDAD < 28;

--FUNCIONES DE BUSQUEDA CON RANGO 
SELECT * FROM EMPLEADO WHERE EDAD BETWEEN 24 AND 29;

--BUSQUEDA POR RANGOS DE ID 1,3,5
SELECT * FROM EMPLEADO WHERE ID_EMPLEADO=1 OR ID_EMPLEADO = 3 OR ID_EMPLEADO = 5;

--USO DE LA FUNCION IN
SELECT * FROM EMPLEADO WHERE ID_EMPLEADO IN (1,3,5);

--USO DE LA FUNCION GROUP BY Y COUNT;
SELECT DEPARTAMENTO FROM EMPLEADO GROUP BY  DEPARTAMENTO;
SELECT DEPARTAMENTO, COUNT (ID_EMPLEADO) AS NO_EMPLEADO FROM EMPLEADO WHERE DEPARTAMENTO IS NOT NULL GROUP BY DEPARTAMENTO;

--CONTAR LOS EMPLEADOS QUE TENAGN MAS DE 25
SELECT COUNT (ID_EMPLEADO) AS TOTAL_EMPLEADOS FROM EMPLEADO WHERE EDAD > 25;

--FUNCION DE ASIGNAION SUM
SELECT SUM(EDAD) AS SUMA_EDADES FROM EMPLEADO WHERE Apellido LIKE 'S%';

--FUNCION DE ASIGNACION MAX
SELECT MAX (EDAD)AS EDAD_MAXIMA FROM EMPLEADO;

--FUNCION DE ASIGNACION MINIMA
SELECT MIN (EDAD)AS EDAD_MINMIA FROM EMPLEADO;

--FUNCION DE AGREGACION AVG
SELECT AVG(EDAD) AS EDAD_PROMEDIO FROM EMPLEADO;

--USO DE LA FUNCION ROUND
SELECT ROUND (AVG (EDAD), 0) AS PROMEDIO_EDAD FROM EMPLEADO;

--UO DE TO CHAR CHAR CON FOTMATO
SELECT TO_CHAR (AVG(EDAD),'fm999.0') AS PROMEDIO_EDAD FROM EMPLEADO WHERE EDAD < 32;

--DARLE UN FORMATO DIFERENTE
--FUNCION CONCAT
SELECT CONCAT(CONCAT(CONCAT(CONCAT('EL EMPLEADO: ', ''), NOMNRE),' '),APELLIDO) AS DETALLE FROM EMPLEADO;

--USO DE 'PIPE' O BARRA VERTICAL ||
SELECT 'EL EMPLEADO(A): ' || NOMNRE 
|| ' ' || apellido || ' DE '|| 
EDAD || ' AÑOS DE EDAD' || ' TRAVAJA EN EL DEPARTAMENTO DE ' 
|| DEPARTAMENTO || ' COMO ' || puesto AS DETALLE_EMPLEADO FROM EMPLEADO;

-- CONSULTA ANIDADA O SUBCONSULTA
SELECT * FROM EMPLEADO WHERE
EDAD=(
    SELECT MAX (EDAD)
    FROM EMPLEADO
    WHERE DEPARTAMENTO = ('Contabilidad')
);

SELECT * FROM EMPLEADO WHERE
EDAD=(
    SELECT MIN (EDAD)
    FROM EMPLEADO
    WHERE DEPARTAMENTO = ('Contabilidad')
);
    
