DELETE FROM COMPUTADORA;
DELETE FROM BIT_COMPUTADORA;

CREATE OR REPLACE TRIGGER TR_I_U_D_COMPUTADORA
AFTER INSERT OR UPDATE OR DELETE ON COMPUTADORA
DECLARE
    LV_ID_BIT NUMBER;
    LV_USUARIO NVARCHAR2(100);
    LV_FECHA DATE;
    LV_MOV NVARCHAR2(100);
BEGIN
    --RECUPERAR ID
    SELECT S_ID_BIT_COMP.NEXTVAL, USER, SYSDATE INTO LV_ID_BIT, LV_USUARIO, LV_FECHA FROM DUAL;
    
    IF INSERTING THEN
        LV_MOV := 'INSERT';
    ELSIF UPDATING THEN
        LV_MOV := 'UPDATE';
    ELSIF DELETING THEN
        LV_MOV := 'DELETE';
    END IF;    
    INSERT INTO BIT_COMPUTADORA (ID_BIT, USUARIO, FECHA_MOV, MOVIMIENTO)
    VALUES(LV_ID_BIT, LV_USUARIO, LV_FECHA, LV_MOV);
END TR_I_U_D_COMPUTADORA;
/

INSERT INTO COMPUTADORA VALUES(1, 'HP', 'PAVILION', 16, 'INTEL CORE i9 12th', 18000);
INSERT INTO COMPUTADORA VALUES(2, 'LENOVO', 'IDEAPAD 5', 16, 'AMD Ryzen 7 5800U', 16500);

SELECT S_ID_BIT_COMP.NEXTVAL FROM DUAL;
SELECT * FROM COMPUTADORA;
SELECT * FROM BIT_COMPUTADORA;

SELECT ID_BIT, USUARIO, FECHA_MOV, MOVIMIENTO FROM BIT_COMPUTADORA;