CREATE TABLE COMPUTADORA(
    ID_COMPU NUMBER,
    MARCA NVARCHAR2(100),
    MODELO NVARCHAR2(100),
    RAM NUMBER,
    PROCESADOR NVARCHAR2(100),
    PRECIO NUMBER,
    CONSTRAINT COMPU_PK PRIMARY KEY (ID_COMPU)
);


CREATE TABLE BIT_COMPUTADORA(
    ID_BIT NUMBER, --LLAVE PRIMARIA
    
    --VALORES NUEVOS
    ID_COMPU NUMBER,
    MARCA NVARCHAR2(100),
    MODELO NVARCHAR2(100),
    RAM NUMBER,
    PROCESADOR NVARCHAR2(100),
    PRECIO NUMBER,
    
    --VALORES VIEJOS
    MARCA_OLD NVARCHAR2(100),
    MODELO_OLD NVARCHAR2(100),
    RAM_OLD NUMBER,
    PROCESADOR_OLD NVARCHAR2(100),
    PRECIO_OLD NUMBER,
    
    --DATOS DE LA TABLA
    USUARIO NVARCHAR2(100),
    FECHA_MOV DATE,
    MOVIMIENTO NVARCHAR2(100),
    
    CONSTRAINT BIT_COMPU_PK PRIMARY KEY (ID_BIT)
);

//TRIGGER PARA INSERTAR DATOS
CREATE OR REPLACE TRIGGER TR_I_COMPUTADORA
AFTER INSERT ON COMPUTADORA
FOR EACH ROW
DECLARE
LV_ID_BIT NUMBER;
LV_USUARIO NVARCHAR2(100);
LV_FECHA DATE;
BEGIN
    SELECT USER INTO LV_USUARIO FROM DUAL;-- OBTENER USUARIO
    SELECT SYSDATE INTO LV_FECHA FROM DUAL;--OBTENER FECHA
    SELECT NVL(MAX(ID_BIT),0) + 1 INTO LV_ID_BIT FROM BIT_COMPUTADORA;--OBTENER  UN ID VALIDO EN AUTOINCREMENTO PARA MI TABLA BITACORA
    
    INSERT INTO BIT_COMPUTADORA(ID_BIT, ID_COMPU, MARCA, MODELO, RAM, PROCESADOR, PRECIO, MARCA_OLD, MODELO_OLD, RAM_OLD, PROCESADOR_OLD, PRECIO_OLD, USUARIO, FECHA_MOV, MOVIMIENTO)
    VALUES (LV_ID_BIT, :NEW.ID_COMPU, :NEW.MARCA, :NEW.MODELO, :NEW.RAM, :NEW.PROCESADOR, :NEW.PRECIO, NULL,NULL,0,null, 0, 
    LV_USUARIO, LV_FECHA, 'INSERT');    
END TR_I_COMPUTADORA;
/

//TRIGGER PARA MODIFICAR DATOS
CREATE OR REPLACE TRIGGER TR_U_COMPUTADORA
AFTER UPDATE ON COMPUTADORA
FOR EACH ROW
DECLARE
    LV_ID_BIT NUMBER;
    LV_USUARIO NVARCHAR2(100);
    LV_FECHA DATE;
BEGIN
    SELECT USER INTO LV_USUARIO FROM DUAL;
    SELECT SYSDATE INTO LV_FECHA FROM DUAL;
    SELECT NVL(MAX(ID_BIT),0) + 1 INTO LV_ID_BIT FROM BIT_COMPUTADORA;
    
    INSERT INTO BIT_COMPUTADORA(ID_BIT, ID_COMPU, MARCA, MODELO, RAM, PROCESADOR, PRECIO, MARCA_OLD, MODELO_OLD, RAM_OLD, PROCESADOR_OLD, PRECIO_OLD, USUARIO, FECHA_MOV, MOVIMIENTO)
    VALUES (LV_ID_BIT, :NEW.ID_COMPU, :NEW.MARCA, :NEW.MODELO, :NEW.RAM, :NEW.PROCESADOR, :NEW.PRECIO, :OLD.MARCA, :OLD.MODELO, :OLD.RAM, :OLD.PROCESADOR, :OLD.PRECIO, 
        LV_USUARIO, LV_FECHA, 'UPDATE'
    );    
END TR_U_COMPUTADORA;
/

//TRIGGER PARA ELIMINAR DATOS
CREATE OR REPLACE TRIGGER TR_D_COMPUTADORA
BEFORE DELETE ON COMPUTADORA
FOR EACH ROW
DECLARE
    LV_ID_BIT NUMBER;
    LV_USUARIO NVARCHAR2(100);
    LV_FECHA DATE;
BEGIN
    SELECT USER INTO LV_USUARIO FROM DUAL;
    SELECT SYSDATE INTO LV_FECHA FROM DUAL;
    SELECT NVL(MAX(ID_BIT),0) + 1 INTO LV_ID_BIT FROM BIT_COMPUTADORA;
    
    INSERT INTO BIT_COMPUTADORA(ID_BIT, ID_COMPU, MARCA, MODELO, RAM, PROCESADOR, PRECIO, MARCA_OLD, MODELO_OLD, RAM_OLD, PROCESADOR_OLD, PRECIO_OLD, USUARIO, FECHA_MOV, MOVIMIENTO)
    VALUES (LV_ID_BIT, :OLD.ID_COMPU, NULL, NULL, NULL, NULL, NULL, :OLD.MARCA, :OLD.MODELO, :OLD.RAM, :OLD.PROCESADOR, :OLD.PRECIO, 
    LV_USUARIO, LV_FECHA, 'DELETE'
    );    
END TR_D_COMPUTADORA;
/

--MUESTRA USUARIO QUE ESTE REALIZANDO UNA ACCION
SELECT USER FROM DUAL;

--MUESTRA LA FECHA
SELECT SYSDATE FROM DUAL;

--MODIFICA EL FORMATO DE COMO SE MUESTRA LA FECHA
ALTER SESSION SET NLS_DATE_FORMAT = 'DD/MM/YYYY HH24:MI:SS';

--CONSULTA AUTOINCREMENTABLE
SELECT NVL(MAX(ID_BIT),0) + 1 AS ID FROM BIT_COMPUTADORA;

INSERT INTO COMPUTADORA VALUES(1, 'HP', 'PAVILION', 16, 'INTEL CORE i9 12th', 18000);

--EJERCICIO;
--1. REALIZAR EL TRIGGER PARA ACTUALIZAR Y PARA ELIMINAR EN LA MISMA BITACORA 
--HACER 5 PRUEBAS

--PRUEBA DE INSERCION
INSERT INTO COMPUTADORA VALUES(2, 'HP', 'PAVILION', 16, 'INTEL CORE i9 12th', 18000);
INSERT INTO COMPUTADORA VALUES(3, 'LENOVO', 'IDEAPAD 5', 16, 'AMD Ryzen 7 5800U', 16500);
INSERT INTO COMPUTADORA VALUES(4, 'ACER', 'ASPIRE 3', 8, 'Intel Core i5-1135G7', 9500);
INSERT INTO COMPUTADORA VALUES(5, 'DELL', '5570', 64, 'Intel Xeon W-11955M', 45000);

COMMIT;

--PRUEBA DE ACTUALIZACION
UPDATE COMPUTADORA SET PRECIO= 10000, RAM=32 WHERE ID_COMPU =2;
UPDATE COMPUTADORA SET MODELO ='A15' WHERE ID_COMPU =4;
UPDATE COMPUTADORA SET PROCESADOR='INTEL CELERON' WHERE ID_COMPU =5;
UPDATE COMPUTADORA SET MARCA='ASUS' WHERE ID_COMPU =2;
UPDATE COMPUTADORA SET PRECIO= 40000 WHERE ID_COMPU =1;
COMMIT;

--PRUEBA DE ELIMINACION
DELETE FROM COMPUTADORA WHERE ID_COMPU = 3;
DELETE FROM COMPUTADORA WHERE RAM = 8;
DELETE FROM COMPUTADORA WHERE PRECIO >= 40000 ;
DELETE FROM COMPUTADORA WHERE MARCA='ASUS';
DELETE FROM COMPUTADORA WHERE ID_COMPU=1;
COMMIT;

--MOSTRAR INFORMACION
SELECT * FROM COMPUTADORA;
SELECT * FROM BIT_COMPUTADORA;