--SECUENCIA O SEQUENCE: SE EMPLEAPARA GENERAR VALORES ENTEROS SECUENCIALES UNICOS Y ASIGNARSELOS A CAMPOS NUMERICOS
--GENERALMENTE PARA LAS CLAVES PRIMARIAS DE LAS TABLAS, GARANTIZANDO QUE SUS VALORES NO SE REPITAN.

CREATE SEQUENCE S_ID_BIT_COMP
START WITH 1
MAXVALUE 999
MINVALUE 1
NOCYCLE;
/

DELETE FROM COMPUTADORA WHERE ID_COMPU = 2;

SELECT S_ID_BIT_COMP.NEXTVAL FROM DUAL;

SELECT * FROM COMPUTADORA;
SELECT * FROM BIT_COMPUTADORA;